## 1. Basic Numpy Array Characteristics

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 2, 5]])

print('Type of numpy array:', type(arr))

print('No. of dimensions:', arr.ndim)

print('Shape of array:', arr.shape)

print('No. of elements:', arr.size)

print('Element type of array:', arr.dtype)

Type of numpy array: <class 'numpy.ndarray'>
No. of dimensions: 2
Shape of array: (2, 3)
No. of elements: 6
Element type of array: int32


## 2. Array Creation

In [2]:
import numpy as np

print('---array creation using list---')
a = np.array([[1, 2, 4],
              [5, 8, 7]], dtype='float')
print(f'{a}\n')

print('---array creation using tuple---')
b = np.array(((1, 2, 3),
             (5, 8, 7)), dtype='float')
print(f'{b}\n')

print('---array creation initialized with zeros---')
c = np.zeros((2, 3), dtype='float')
print(f'{c}\n')

print('---array creation initialized specific value which data type is complex number---')
d = np.full((2, 3), 6, dtype='complex')
print(f'{d}\n')

print('--array creation initialized with random values')
e = np.random.random((2, 2))
print(f'{e}\n')

print('---array creation of sequence of numbers i.e. like range() built-in python function---')
f = np.arange(0, 30, 5) # start, end, step
print(f'{f}\n')

print('---array creation of sequence of values evenly spaced---')
g = np.linspace(0, 5, 10)
print(f'{g}\n')

# reshaping
print('---reshaping array---')
foo = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
bar = foo.reshape(2, 2, 3)
print('from')
print(foo)
print('to')
print(bar)

# flatten
print('---flatten array---')
baz = np.array([[1, 2, 3],
                [4, 5, 6]])
print('from')
print(baz)
print('to')
flt = baz.flatten()
print(flt)

---array creation using list---
[[1. 2. 4.]
 [5. 8. 7.]]

---array creation using tuple---
[[1. 2. 3.]
 [5. 8. 7.]]

---array creation initialized with zeros---
[[0. 0. 0.]
 [0. 0. 0.]]

---array creation initialized specific value which data type is complex number---
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

--array creation initialized with random values
[[0.26515316 0.35833154]
 [0.69470957 0.29252421]]

---array creation of sequence of numbers i.e. like range() built-in python function---
[ 0  5 10 15 20 25]

---array creation of sequence of values evenly spaced---
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

---reshaping array---
from
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
to
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
---flatten array---
from
[[1 2 3]
 [4 5 6]]
to
[1 2 3 4 5 6]


### Array Slicing and Indexing

In [3]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
               [4, -0.5, 6, 0],
               [2.6, 0, 7, 8],
               [3, -7, 4, 2.0]])

# slicing array
foo = arr[:2, ::2]
print(foo)

# integer array indexing
bar = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", bar)

# boolean array indexing
condition = arr > 0
baz = arr[condition]
print ("\nElements greater than 0:\n", baz)

[[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


## 4. Basic Operations

### 4.1. Operation on single array

In [4]:
import numpy as np

foo = np.array([1, 2, 3, 4, 5])

# add 1 to every element
print(f'{foo + 1}')

# subtract 1 to every element
print(f'{foo - 1}')

# multiply 2 to every element
print(f'{foo * 2}')

# square each element
print(f'{foo ** 2}\n')

# transpose
bar = np.array([[1,2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(bar)
print('Transpose')
print(bar.T)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[ 1  4  9 16 25]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 4.2. Unary Operators

In [8]:
import numpy as np

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

print('maximum elements:', arr.max())
print('row-wise maximum elements:', arr.max(axis=1))
print('column-wise maximum elements:', arr.max(axis=0))

print('minimum elements:', arr.min())
print('sum of all elements:', arr.sum())
print('sum of row-wise elements:',  arr.sum(axis=1))
print('sum of column-wise elements:',  arr.sum(axis=0))
print('Cumulative sum along each row:\n', arr.cumsum(axis=1))

maximum elements: 9
row-wise maximum elements: [6 7 9]
column-wise maximum elements: [4 7 9]
minimum elements: 1
sum of all elements: 38
sum of row-wise elements: [12 13 13]
sum of column-wise elements: [ 8 13 17]
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


### 4.3. Binary Operators

In [10]:
import numpy as np

foo = np.array([[1, 2],
                [4, 5]])

bar = np.array([[4, 1],
                [2, 3]])

baz = foo + bar
print('Array Summation\n', baz)

qux = foo * bar
print('Array Multiplication: element-wise\n', qux)

tar = foo / bar
print('Array Division\n', tar)

taz = foo.dot(bar)
print('Matrix Multiplication\n', taz)

Array Summation
 [[5 3]
 [6 8]]
Array Multiplication: element-wise
 [[ 4  2]
 [ 8 15]]
Array Division
 [[0.25       2.        ]
 [2.         1.66666667]]
Matrix Multiplication
 [[ 8  7]
 [26 19]]


### 4.4 Universal Functions

In [ ]:
import numpy as np

foo = np.array([0, np.pi/2, np.pi])
print('Sine values of array elements', np.sin(foo))

bar = np.array([0, 1, 2, 3])
print('Exponent of array elements', np.exp(bar))

print('Square root of array elements', np.sqrt(bar))

## 5. Sorting Array

In [30]:
import numpy as np

foo = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])

# sorted array
print('Sorted Array: ', np.sort(foo, axis=None))

# sort array row-wise
print('Row-wise Sorted Array:\n', np.sort(foo, axis=1)) # axis=1 is default
print('Column-wise Sorted Array:\n', np.sort(foo, axis=0))

values = [('Hrithik', 2009, 8.6), ('Ajay', 2008, 8.7),
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

dtypes = [('name', 'S10'), ('grad_year', int), ('gpa', float)]
bar = np.array(values, dtype=dtypes)
print(bar.shape)
print('Graduation GPA\n', bar)
print('Array Sorted by name\n', np.sort(bar, order='name'))
print('Array sorted by graduation year and then gpa\n', np.sort(bar, order = ['grad_year', 'gpa']))

Sorted Array:  [-1  0  1  2  3  4  4  5  6]
Row-wise Sorted Array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column-wise Sorted Array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
(4,)
Graduation GPA
 [(b'Hrithik', 2009, 8.6) (b'Ajay', 2008, 8.7) (b'Pankaj', 2008, 7.9)
 (b'Aakash', 2009, 9. )]
Array Sorted by name
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.6)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then gpa
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.6)
 (b'Aakash', 2009, 9. )]
