Basic Numpy Array Characteristics

In [39]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 2, 5]])

print('Array is of type: ', type(arr))

print('No. of dimensions: ', arr.ndim)

print('Shape of array: ', arr.shape)

print('Size of array: ', arr.size)

print('Array stores elements of type', arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type int32


Array Creation

In [40]:
import numpy as np

print('---array creation using list---')
a = np.array([[1, 2, 4],
              [5, 8, 7]], dtype='float')
print(f'{a}\n')

print('---array creation using tuple---')
b = np.array(((1, 2, 3),
             (5, 8, 7)), dtype='float')
print(f'{b}\n')

print('---array creation initialized with zeros---')
c = np.zeros((2, 3), dtype='float')
print(f'{c}\n')

print('---array creation initialized specific value which data type is complex number---')
d = np.full((2, 3), 6, dtype='complex')
print(f'{d}\n')

print('--array creation initialized with random values')
e = np.random.random((2, 2))
print(f'{e}\n')

print('---array creation of sequence of numbers i.e. like range() built-in python function---')
f = np.arange(0, 30, 5) # start, end, step
print(f'{f}\n')

print('---array creation of sequence of values evenly spaced---')
g = np.linspace(0, 5, 10)
print(f'{g}\n')

# reshaping
print('---reshaping array---')
foo = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
bar = foo.reshape(2, 2, 3)
print('from')
print(foo)
print('to')
print(bar)

# flatten
print('---flatten array---')
baz = np.array([[1, 2, 3],
                [4, 5, 6]])
print('from')
print(baz)
print('to')
flt = baz.flatten()
print(flt)

---array creation using list---
[[1. 2. 4.]
 [5. 8. 7.]]

---array creation using tuple---
[[1. 2. 3.]
 [5. 8. 7.]]

---array creation initialized with zeros---
[[0. 0. 0.]
 [0. 0. 0.]]

---array creation initialized specific value which data type is complex number---
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

--array creation initialized with random values
[[0.83337259 0.78055917]
 [0.87371314 0.64745061]]

---array creation of sequence of numbers i.e. like range() built-in python function---
[ 0  5 10 15 20 25]

---array creation of sequence of values evenly spaced---
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

---reshaping array---
from
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
to
[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
---flatten array---
from
[[1 2 3]
 [4 5 6]]
to
[1 2 3 4 5 6]
