### Python Array Module for Creating Array

In [4]:
import array

foo = array.array('i', [1, 2, 3, 4, 5])
print('Created Array:', end=' ')
for num in foo:
    print(num, end=' ')

Created Array: 1 2 3 4 5 

### Numpy Module for Creating Array

In [35]:
import numpy as np

# random values
foo = np.empty([3, 3], dtype=int)
print(foo, '\n')

# zero values
bar = np.zeros([3, 3], dtype=float)
print(bar, '\n')

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [      0   32762       0]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

