### Python Array Module for Creating Array

In [4]:
import array

foo = array.array('i', [1, 2, 3, 4, 5])
print('Created Array:', end=' ')
for num in foo:
    print(num, end=' ')

Created Array: 1 2 3 4 5 

### Numpy Module for Creating Array

In [35]:
import numpy as np

# random values
foo = np.empty([3, 3], dtype=int)
print(foo, '\n')

# zero values
bar = np.zeros([3, 3], dtype=float)
print(bar, '\n')

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [      0   32762       0]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [43]:
import numpy as np

foo = np.arange(8)
print(foo, '\n')

bar = np.reshape(foo, (2,4))
print(bar, '\n')

baz = np.reshape(foo, (4, 2))
print(baz, '\n')

tar = np.reshape(foo, (2, 2, 2))
print(tar)

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### numpy.arrange(start, end, step)

In [47]:
import numpy as np

start, end, step = 0, 10, 2
print(np.arange(start, end ,step))

start, end, step = 0, 1, 0.1 # float available which is not built-in range() function
print(np.arange(start, end, step))

[0 2 4 6 8]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
